apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: myportfolio
  labels:
    app: portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: 262101604988.dkr.ecr.us-east-1.amazonaws.com/zera18/myportfolio:0.0.1-SNAPSHOT-55
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
