apiVersion: v1
kind: Service
metadata:
  name: portfolio-lb
  namespace: myportfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio-app
  ports:
    - protocol: tcp
      port: 8080
      targetPort: 8080