apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
  namespace: myportfolio
spec:
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer